/**
 * Generated by orval v8.17.0 🍺
 * Do not edit manually.
 * 故桌 Narratable API
 * 故桌（Narratable）实时跑团平台的后台 API
 * OpenAPI spec version: 1.0
 */
import type { GithubComNarraTableBackendPkgProtocolRoomType } from './githubComNarraTableBackendPkgProtocolRoomType.ts';

export interface GithubComNarraTableBackendPkgProtocolRoom {
  createdAt?: string;
  description?: string;
  isArchived?: boolean;
  lastActiveAt?: string;
  name?: string;
  roomId?: string;
  /** 排序权重，越小越靠前 */
  sortOrder?: number;
  spaceId?: string;
  type?: GithubComNarraTableBackendPkgProtocolRoomType;
  /** 私密房的可见成员，nil = 全体可见 */
  visibleMemberIds?: string[];
}
