/**
 * Generated by orval v8.17.0 🍺
 * Do not edit manually.
 * 故桌 Narratable API
 * 故桌（Narratable）实时跑团平台的后台 API
 * OpenAPI spec version: 1.0
 */

export type GithubComNarraTableBackendPkgProtocolMaskType = typeof GithubComNarraTableBackendPkgProtocolMaskType[keyof typeof GithubComNarraTableBackendPkgProtocolMaskType];


export const GithubComNarraTableBackendPkgProtocolMaskType = {
  /** 玩家角色面具 */
  MaskCharacter: 'character',
  /** NPC 面具 */
  MaskNPC: 'npc',
  /** 系统面具（骰娘等） */
  MaskSystem: 'system',
  /** GM 面具 */
  MaskGM: 'gm',
} as const;
