/**
 * Generated by orval v8.17.0 🍺
 * Do not edit manually.
 * 故桌 Narratable API
 * 故桌（Narratable）实时跑团平台的后台 API
 * OpenAPI spec version: 1.0
 */

export type GithubComNarraTableBackendPkgProtocolWSErrorCode = typeof GithubComNarraTableBackendPkgProtocolWSErrorCode[keyof typeof GithubComNarraTableBackendPkgProtocolWSErrorCode];


export const GithubComNarraTableBackendPkgProtocolWSErrorCode = {
  WSErrorInvalidCommand: 'invalid_command',
  WSErrorUnauthenticated: 'unauthenticated',
  WSErrorUnauthorized: 'unauthorized',
  WSErrorAccountInactive: 'account_inactive',
  WSErrorRoomNotFound: 'room_not_found',
  WSErrorInvalidMessage: 'invalid_message',
  WSErrorPersistence: 'persistence_failed',
  WSErrorConnectionLimit: 'connection_limit',
} as const;
