/**
 * Generated by orval v8.17.0 🍺
 * Do not edit manually.
 * 故桌 Narratable API
 * 故桌（Narratable）实时跑团平台的后台 API
 * OpenAPI spec version: 1.0
 */

export type GithubComNarraTableBackendPkgProtocolRoomType = typeof GithubComNarraTableBackendPkgProtocolRoomType[keyof typeof GithubComNarraTableBackendPkgProtocolRoomType];


export const GithubComNarraTableBackendPkgProtocolRoomType = {
  /** 会话房（主游戏房） */
  RoomSession: 'session',
  /** 资料房（角色卡、设定存档） */
  RoomReference: 'reference',
  /** 私密房（仅指定成员可见） */
  RoomPrivate: 'private',
  /** 工具房（骰娘专用、日志） */
  RoomTool: 'tool',
} as const;
