/**
 * Generated by orval v8.17.0 🍺
 * Do not edit manually.
 * 故桌 Narratable API
 * 故桌（Narratable）实时跑团平台的后台 API
 * OpenAPI spec version: 1.0
 */

export interface GithubComNarraTableBackendPkgProtocolResult {
  /** 成功时的输出数据 */
  data?: unknown;
  /** 失败时的错误信息 */
  error?: string;
  success?: boolean;
}
