/**
 * Generated by orval v8.17.0 🍺
 * Do not edit manually.
 * 故桌 Narratable API
 * 故桌（Narratable）实时跑团平台的后台 API
 * OpenAPI spec version: 1.0
 */

export type GithubComNarraTableBackendPkgProtocolEventType = typeof GithubComNarraTableBackendPkgProtocolEventType[keyof typeof GithubComNarraTableBackendPkgProtocolEventType];


export const GithubComNarraTableBackendPkgProtocolEventType = {
  EventMessageCreated: 'message.created',
  EventMessageUpdated: 'message.updated',
  EventMessageDeleted: 'message.deleted',
  EventMessageRejected: 'message.rejected',
  EventAuthResult: 'auth.result',
  EventPresenceJoined: 'presence.joined',
  EventPresenceLeft: 'presence.left',
  EventVeilRevealed: 'veil.revealed',
  EventConnectionGap: 'connection.gap',
} as const;
