/**
 * Generated by orval v8.17.0 🍺
 * Do not edit manually.
 * 故桌 Narratable API
 * 故桌（Narratable）实时跑团平台的后台 API
 * OpenAPI spec version: 1.0
 */
import type { GithubComNarraTableBackendPkgProtocolResourceKind } from './githubComNarraTableBackendPkgProtocolResourceKind.ts';
import type { GithubComNarraTableBackendPkgProtocolResourceMetadata } from './githubComNarraTableBackendPkgProtocolResourceMetadata.ts';

export interface GithubComNarraTableBackendPkgProtocolResource {
  checksum?: string;
  createdAt?: string;
  kind?: GithubComNarraTableBackendPkgProtocolResourceKind;
  messageId?: string;
  metadata?: GithubComNarraTableBackendPkgProtocolResourceMetadata;
  mimeType?: string;
  name?: string;
  resourceId?: string;
  roomId?: string;
  sizeBytes?: number;
  spaceId?: string;
  updatedAt?: string;
  uploadedBy?: string;
  uri?: string;
}
