/**
 * Generated by orval v8.17.0 🍺
 * Do not edit manually.
 * 故桌 Narratable API
 * 故桌（Narratable）实时跑团平台的后台 API
 * OpenAPI spec version: 1.0
 */
import type { GithubComNarraTableBackendPkgProtocolBlock } from './githubComNarraTableBackendPkgProtocolBlock.ts';
import type { GithubComNarraTableBackendPkgProtocolClueContent } from './githubComNarraTableBackendPkgProtocolClueContent.ts';
import type { GithubComNarraTableBackendPkgProtocolEditRecord } from './githubComNarraTableBackendPkgProtocolEditRecord.ts';
import type { GithubComNarraTableBackendPkgProtocolForwardContent } from './githubComNarraTableBackendPkgProtocolForwardContent.ts';
import type { GithubComNarraTableBackendPkgProtocolMessageType } from './githubComNarraTableBackendPkgProtocolMessageType.ts';
import type { GithubComNarraTableBackendPkgProtocolParam } from './githubComNarraTableBackendPkgProtocolParam.ts';
import type { GithubComNarraTableBackendPkgProtocolResult } from './githubComNarraTableBackendPkgProtocolResult.ts';
import type { GithubComNarraTableBackendPkgProtocolSender } from './githubComNarraTableBackendPkgProtocolSender.ts';
import type { GithubComNarraTableBackendPkgProtocolVeil } from './githubComNarraTableBackendPkgProtocolVeil.ts';

export interface GithubComNarraTableBackendPkgProtocolMessage {
  /** clue 类型：线索数据 */
  clue?: GithubComNarraTableBackendPkgProtocolClueContent;
  /** command 类型：指令名 */
  command?: string;
  /** chat 类型：块列表 */
  content?: GithubComNarraTableBackendPkgProtocolBlock[];
  /** 是否已删除（软删除） */
  deleted?: boolean;
  /** ---- 编辑历史 ---- */
  editHistory?: GithubComNarraTableBackendPkgProtocolEditRecord[];
  /** 是否折叠 */
  folded?: boolean;
  /** forward 类型：合并转发内容 */
  forward?: GithubComNarraTableBackendPkgProtocolForwardContent;
  messageId?: string;
  /** command 类型：指令参数 */
  params?: GithubComNarraTableBackendPkgProtocolParam[];
  /** 是否置顶 */
  pinned?: boolean;
  /** command 类型：原始指令文本（如 ".r 3d6+2 力量检定"） */
  raw?: string;
  /** command 类型：指令响应对应的原始消息 ID */
  refMessageId?: string;
  /** 指令执行结果（服务端计算后填入） */
  result?: GithubComNarraTableBackendPkgProtocolResult;
  roomId?: string;
  /** ---- 时间与状态 ---- */
  sendTime?: string;
  /** 发送者 */
  sender?: GithubComNarraTableBackendPkgProtocolSender;
  spaceId?: string;
  type?: GithubComNarraTableBackendPkgProtocolMessageType;
  updateTime?: string;
  /** ---- 可见性 ---- */
  veil?: GithubComNarraTableBackendPkgProtocolVeil;
}
