/**
 * Generated by orval v8.17.0 🍺
 * Do not edit manually.
 * 故桌 Narratable API
 * 故桌（Narratable）实时跑团平台的后台 API
 * OpenAPI spec version: 1.0
 */

export interface GithubComNarraTableBackendPkgProtocolEditRecord {
  /** 编辑者 */
  editBy?: string;
  /** 编辑时间 */
  editTime?: string;
  /** 编辑前的内容或指令 */
  previousRaw?: unknown;
}
