/**
 * Generated by orval v8.17.0 🍺
 * Do not edit manually.
 * 故桌 Narratable API
 * 故桌（Narratable）实时跑团平台的后台 API
 * OpenAPI spec version: 1.0
 */

export type GithubComNarraTableBackendPkgProtocolMessageType = typeof GithubComNarraTableBackendPkgProtocolMessageType[keyof typeof GithubComNarraTableBackendPkgProtocolMessageType];


export const GithubComNarraTableBackendPkgProtocolMessageType = {
  MsgTypeChat: 'chat',
  MsgTypeClue: 'clue',
  MsgTypeCommand: 'command',
  MsgTypeSystem: 'system',
  MsgTypeForward: 'forward',
} as const;
