/**
 * Generated by orval v8.17.0 🍺
 * Do not edit manually.
 * 故桌 Narratable API
 * 故桌（Narratable）实时跑团平台的后台 API
 * OpenAPI spec version: 1.0
 */

export type GithubComNarraTableBackendPkgProtocolVisibility = typeof GithubComNarraTableBackendPkgProtocolVisibility[keyof typeof GithubComNarraTableBackendPkgProtocolVisibility];


export const GithubComNarraTableBackendPkgProtocolVisibility = {
  VisibilityAll: 'all',
  VisibilityGMOnly: 'gm_only',
  VisibilityCustom: 'custom',
  VisibilityGMAndCustom: 'gm_and_custom',
} as const;
