/**
 * Generated by orval v8.17.0 🍺
 * Do not edit manually.
 * 故桌 Narratable API
 * 故桌（Narratable）实时跑团平台的后台 API
 * OpenAPI spec version: 1.0
 */
import type { GithubComNarraTableBackendPkgProtocolMaskAvatars } from './githubComNarraTableBackendPkgProtocolMaskAvatars.ts';
import type { GithubComNarraTableBackendPkgProtocolMaskType } from './githubComNarraTableBackendPkgProtocolMaskType.ts';

export interface GithubComNarraTableBackendPkgProtocolMask {
  avatars?: GithubComNarraTableBackendPkgProtocolMaskAvatars;
  characterCards?: string[];
  createdAt?: string;
  currentAvatarId?: string;
  defaultAvatarId?: string;
  /** 是否为默认面具 */
  isDefault?: boolean;
  maskId?: string;
  name?: string;
  spaceId?: string;
  type?: GithubComNarraTableBackendPkgProtocolMaskType;
  updatedAt?: string;
  /** 可使用此面具的用户列表 */
  userIds?: string[];
}
