/**
 * Generated by orval v8.17.0 🍺
 * Do not edit manually.
 * 故桌 Narratable API
 * 故桌（Narratable）实时跑团平台的后台 API
 * OpenAPI spec version: 1.0
 */
import type { GithubComNarraTableBackendPkgProtocolPluginConfigSchema } from './githubComNarraTableBackendPkgProtocolPluginConfigSchema.ts';

export interface GithubComNarraTableBackendPkgProtocolPlugin {
  author?: string;
  builtIn?: boolean;
  characterDataType?: string;
  configSchema?: GithubComNarraTableBackendPkgProtocolPluginConfigSchema;
  createdAt?: string;
  description?: string;
  displayName?: string;
  enabled?: boolean;
  name?: string;
  pluginId?: string;
  source?: string;
  updatedAt?: string;
  version?: string;
}
