/**
 * Generated by orval v8.17.0 🍺
 * Do not edit manually.
 * 故桌 Narratable API
 * 故桌（Narratable）实时跑团平台的后台 API
 * OpenAPI spec version: 1.0
 */
import type { GithubComNarraTableBackendPkgProtocolMentionTarget } from './githubComNarraTableBackendPkgProtocolMentionTarget.ts';

export interface GithubComNarraTableBackendPkgProtocolInline {
  bold?: boolean;
  displayText?: string;
  /** face */
  faceId?: string;
  italic?: boolean;
  strikethrough?: boolean;
  /** mention */
  target?: GithubComNarraTableBackendPkgProtocolMentionTarget;
  /** text */
  text?: string;
  type?: string;
  underline?: boolean;
}
