/**
 * Generated by orval v8.17.0 🍺
 * Do not edit manually.
 * 故桌 Narratable API
 * 故桌（Narratable）实时跑团平台的后台 API
 * OpenAPI spec version: 1.0
 */

export interface GithubComNarraTableBackendPkgProtocolClueContent {
  description?: string;
  imageUrl?: string;
  /** 是否已被发现 */
  isDiscovered?: boolean;
  tags?: string[];
  title?: string;
}
