/**
 * Generated by orval v8.17.0 🍺
 * Do not edit manually.
 * 故桌 Narratable API
 * 故桌（Narratable）实时跑团平台的后台 API
 * OpenAPI spec version: 1.0
 */
import type { GithubComNarraTableBackendPkgProtocolBlock } from './githubComNarraTableBackendPkgProtocolBlock.ts';
import type { GithubComNarraTableBackendPkgProtocolForwardContent } from './githubComNarraTableBackendPkgProtocolForwardContent.ts';
import type { GithubComNarraTableBackendPkgProtocolMessageType } from './githubComNarraTableBackendPkgProtocolMessageType.ts';

export interface GithubComNarraTableBackendPkgProtocolForwardedMessage {
  avatarId?: string;
  blocks?: GithubComNarraTableBackendPkgProtocolBlock[];
  forward?: GithubComNarraTableBackendPkgProtocolForwardContent;
  senderMaskId?: string;
  senderName?: string;
  sourceMessageId?: string;
  sourceRoomId?: string;
  timestamp?: string;
  type?: GithubComNarraTableBackendPkgProtocolMessageType;
}
