/**
 * Generated by orval v8.17.0 🍺
 * Do not edit manually.
 * 故桌 Narratable API
 * 故桌（Narratable）实时跑团平台的后台 API
 * OpenAPI spec version: 1.0
 */
import type { GithubComNarraTableBackendPkgProtocolVisibility } from './githubComNarraTableBackendPkgProtocolVisibility.ts';

export interface GithubComNarraTableBackendPkgProtocolVeil {
  /** 结团后自动公开 */
  revealOnSpaceClose?: boolean;
  visibility?: GithubComNarraTableBackendPkgProtocolVisibility;
  /** custom / gm_and_custom 时使用 */
  visibleTo?: string[];
}
