/**
 * Generated by orval v8.17.0 🍺
 * Do not edit manually.
 * 故桌 Narratable API
 * 故桌（Narratable）实时跑团平台的后台 API
 * OpenAPI spec version: 1.0
 */
import type { GithubComNarraTableBackendPkgProtocolInline } from './githubComNarraTableBackendPkgProtocolInline.ts';
import type { GithubComNarraTableBackendPkgProtocolReplyPreview } from './githubComNarraTableBackendPkgProtocolReplyPreview.ts';

export interface GithubComNarraTableBackendPkgProtocolBlock {
  alt?: string;
  caption?: string;
  /** paragraph */
  children?: GithubComNarraTableBackendPkgProtocolInline[];
  /** 时长（秒） */
  duration?: number;
  /** table */
  headers?: string[];
  height?: number;
  /** divider */
  label?: string;
  /** reply */
  messageId?: string;
  preview?: GithubComNarraTableBackendPkgProtocolReplyPreview;
  /** image */
  resourceId?: string;
  rows?: string[][];
  /** audio */
  title?: string;
  type?: string;
  width?: number;
}
