/**
 * Generated by orval v8.17.0 🍺
 * Do not edit manually.
 * 故桌 Narratable API
 * 故桌（Narratable）实时跑团平台的后台 API
 * OpenAPI spec version: 1.0
 */
import type { InternalHandlerWSCommandDoc } from './internalHandlerWSCommandDoc.ts';
import type { InternalHandlerWSEventDoc } from './internalHandlerWSEventDoc.ts';

export interface InternalHandlerWSFrameExamples {
  authCommand?: InternalHandlerWSCommandDoc;
  authResult?: InternalHandlerWSEventDoc;
  messageCreated?: InternalHandlerWSEventDoc;
  messageDeleted?: InternalHandlerWSEventDoc;
  messageRejected?: InternalHandlerWSEventDoc;
  messageSend?: InternalHandlerWSCommandDoc;
  messageUpdated?: InternalHandlerWSEventDoc;
  presenceJoined?: InternalHandlerWSEventDoc;
  presenceLeft?: InternalHandlerWSEventDoc;
  veilRevealed?: InternalHandlerWSEventDoc;
}
