/**
 * Generated by orval v8.17.0 🍺
 * Do not edit manually.
 * 故桌 Narratable API
 * 故桌（Narratable）实时跑团平台的后台 API
 * OpenAPI spec version: 1.0
 */
import type { GithubComNarraTableBackendPkgProtocolMemberRole } from './githubComNarraTableBackendPkgProtocolMemberRole.ts';

export interface InternalHandlerSpaceSummary {
  createdAt: string;
  lastActiveAt: string;
  /**
     * @minimum 0
     * @maximum 100
     */
  memberCount: number;
  myRole?: GithubComNarraTableBackendPkgProtocolMemberRole;
  name: string;
  ownerId: string;
  spaceId: string;
  status: string;
}
