/**
 * Generated by orval v8.17.0 🍺
 * Do not edit manually.
 * 故桌 Narratable API
 * 故桌（Narratable）实时跑团平台的后台 API
 * OpenAPI spec version: 1.0
 */
import type { GithubComNarraTableBackendPkgProtocolMaskType } from './githubComNarraTableBackendPkgProtocolMaskType.ts';
import type { InternalHandlerCreateMaskRequestAvatars } from './internalHandlerCreateMaskRequestAvatars.ts';

export interface InternalHandlerCreateMaskRequest {
  avatars?: InternalHandlerCreateMaskRequestAvatars;
  currentAvatarId?: string;
  defaultAvatarId?: string;
  name?: string;
  type: GithubComNarraTableBackendPkgProtocolMaskType;
}
