/**
 * Generated by orval v8.17.0 🍺
 * Do not edit manually.
 * 故桌 Narratable API
 * 故桌（Narratable）实时跑团平台的后台 API
 * OpenAPI spec version: 1.0
 */
import type { GithubComNarraTableBackendInternalModelUserStatus } from './githubComNarraTableBackendInternalModelUserStatus.ts';

export interface InternalHandlerAdminUserResponse {
  avatar?: string;
  createdAt?: string;
  email?: string;
  id?: string;
  mustChangePassword?: boolean;
  nickname?: string;
  status?: GithubComNarraTableBackendInternalModelUserStatus;
  updatedAt?: string;
  username?: string;
}
