/**
 * Generated by orval v8.17.0 🍺
 * Do not edit manually.
 * 故桌 Narratable API
 * 故桌（Narratable）实时跑团平台的后台 API
 * OpenAPI spec version: 1.0
 */

export interface InternalHandlerCreateAdminPluginRequest {
  author?: string;
  characterDataType?: string;
  configSchema?: string;
  description?: string;
  displayName: string;
  enabled?: boolean;
  name: string;
  source: string;
  version: string;
}
