/**
 * Generated by orval v8.17.0 🍺
 * Do not edit manually.
 * 故桌 Narratable API
 * 故桌（Narratable）实时跑团平台的后台 API
 * OpenAPI spec version: 1.0
 */
import type { GithubComNarraTableBackendPkgProtocolMember } from './githubComNarraTableBackendPkgProtocolMember.ts';
import type { GithubComNarraTableBackendPkgProtocolModuleSource } from './githubComNarraTableBackendPkgProtocolModuleSource.ts';

export interface InternalHandlerSpaceDetail {
  createdAt?: string;
  description?: string;
  members?: GithubComNarraTableBackendPkgProtocolMember[];
  moduleSource?: GithubComNarraTableBackendPkgProtocolModuleSource;
  name?: string;
  ownerId?: string;
  spaceId?: string;
  status?: string;
  updatedAt?: string;
}
