/**
 * Generated by orval v8.17.0 🍺
 * Do not edit manually.
 * 故桌 Narratable API
 * 故桌（Narratable）实时跑团平台的后台 API
 * OpenAPI spec version: 1.0
 */
import type { InternalHandlerUserResponse } from './internalHandlerUserResponse.ts';

export interface InternalHandlerAuthResponse {
  accessToken: string;
  /**
     * @minimum 0
     * @maximum 86400
     */
  expiresIn: number;
  refreshToken: string;
  user: InternalHandlerUserResponse;
}
