/**
 * Generated by orval v8.17.0 🍺
 * Do not edit manually.
 * 故桌 Narratable API
 * 故桌（Narratable）实时跑团平台的后台 API
 * OpenAPI spec version: 1.0
 */
import type { GithubComNarraTableBackendPkgProtocolRoomType } from './githubComNarraTableBackendPkgProtocolRoomType.ts';

export interface InternalHandlerRoomSummary {
  hasJoinCode?: boolean;
  isArchived?: boolean;
  lastActiveAt?: string;
  memberCount?: number;
  name?: string;
  roomId?: string;
  sortOrder?: number;
  spaceId?: string;
  type?: GithubComNarraTableBackendPkgProtocolRoomType;
}
