/**
 * Generated by orval v8.17.0 🍺
 * Do not edit manually.
 * 故桌 Narratable API
 * 故桌（Narratable）实时跑团平台的后台 API
 * OpenAPI spec version: 1.0
 */
import type { GithubComNarraTableBackendPkgProtocolRoom } from './githubComNarraTableBackendPkgProtocolRoom.ts';

export interface InternalHandlerCreateRoomResponse {
  joinCode?: string;
  room?: GithubComNarraTableBackendPkgProtocolRoom;
}
