/**
 * Generated by orval v8.17.0 🍺
 * Do not edit manually.
 * 故桌 Narratable API
 * 故桌（Narratable）实时跑团平台的后台 API
 * OpenAPI spec version: 1.0
 */

export type PostApiSpacesSpaceIdResourcesUploadBody = {
  /** 资源文件 */
  file: Blob;
  /** 资源名称，默认文件名 */
  name?: string;
  /** 资源类型 image/audio/video/document/archive/other */
  kind?: string;
  /** 关联房间ID */
  roomId?: string;
  /** 关联消息ID */
  messageId?: string;
  /** JSON object 字符串 */
  metadata?: string;
};
