/**
 * Generated by orval v8.17.0 🍺
 * Do not edit manually.
 * 故桌 Narratable API
 * 故桌（Narratable）实时跑团平台的后台 API
 * OpenAPI spec version: 1.0
 */

export type PostApiResourcesUploadBody = {
  /** 资源文件 */
  file: Blob;
  /** 资源名称，默认文件名 */
  name?: string;
  /** 资源类型 image/audio/video/document/archive/other */
  kind?: string;
  /** 资源类型别名，兼容 kind */
  type?: string;
  /** 可选空间ID；不传则保存为全局资源 */
  spaceId?: string;
};
